### ISSUE TITLE
funzionalita`?

### ISSUE THREAD

**Issue by marte-git** [JohnnyYuVe/CONSEGNA-3#1]
cosa e` la 
"funzionalità contenuto nei codici integrativi, da lei condiviso, che permetteva la stampa parziale dei contenuti."

**Comment by JohnnyYuVe** [comment]
tra i pdf da lei condiviso, in particolare  la seconda parte di xml, è presente la cartella dove sono contenuti esempi sulla codificazione con DOM in particolare c'è un file tra questi, che permetteva di stampare tot. elementi per volta all'interno della pagina.
Ho Sfruttato quel piccolo pezzo di codice per stampare tot. elementi per pagina.
