### ISSUE TITLE
sito_web

### ISSUE THREAD

**Issue by marte-git** [JohnnyYuVe/CONSEGNA-3#2]
e` un nome troppo generico ... se foste in piu` di uno a sceglerlo potrebbe creare interessanti problemi

**Comment by JohnnyYuVe** [comment]
salve prof, non riesco a visualizzare il problema che si potrebbe generare utilizzando questo nome, considerando che per accedere a tale database bisogna stabilire una connessione con il mio phpmyadmin.

**Comment by marte-git** [comment]
io ricevo il suo sistema e lo istallo su una mia macchina, in un mio webserver e nel mio mariadb (dove viene creato "sito_web" ...

"sito_web" e` un nome troppo generico, che chiunque potrebbe usare, creando problemi ... quindi e` consigliabile che il nome sia diverso "3-compito-nome.cognome" non sarebbe male ...
